import { Inter } from 'next/font/google';
import './globals.css';
import Provider from '@/store';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Begüm Ircı',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='tr'>
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
